<div class="col-md-8 main-content">
<div class="container">
  <!-- ADS -->
  <div class="row mt-5">
      <div class="col-md-8">
        <div class="ads-1">
          <div class="text-button">
            <p>Tow High-end Materials</p>
            <div class="header-icon">
              <a style="color: #ffffff" type="button">Shop Now</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
          <div class="ads-2">
            <div class="text-ads-2">
              <p class="text-regular">SMALL THING</p>
              <p>MAKE DIFFERENT</p>
            </div>
          </div>
          <div class="ads-3">
            <div class="text-ads-3">
              <p class="text-regular">FOLIO</p>
              <p>BACKPACK</p>
              <a style="color: #ffffff" type="button">Shop Now</a>
            </div>  
        </div>
      </div>      
  </div>
  <!-- PRODUCTIONS -->
  <div class="production-title">
    <p class="text-logo">F R A N C O</p>
    <p class="title-p">FEATURED ITEMS</p>
    <div class="border-title"></div>
  </div>

  <div class="product">
    <div class="production-content">
      <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
          <div class="product-top">
            <img src="{{view url="images/productions/01_homepage_4.jpg"}}" />
            <a href="#" type="button">ADD TO CARD</a>
          </div>
          <div class="product-desc">
            <p>Suspendisse id volutpat</p>
            <div class="rate mt-1">
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star"></i></span>
            </div>
            <div class="d-flex mt-1">
              <p class="old-price">$99.00</p>
              <p class="new-price">$84.00</p>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
            <div class="product-top">
              <img src="/images/productions/01_homepage_5.jpg">
              <a href="#" type="button">ADD TO CARD</a>
            </div>
            <div class="product-desc">
              <p>Lorem ipsum dolor</p>
              <div class="rate mt-1">
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star"></i></span>
              </div>
              <div class="d-flex mt-1">
                <p class="old-price">$99.00</p>
                <p class="new-price">$84.00</p>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
              <div class="product-top">
                <img src="/images/productions/01_homepage_6.jpg">
                <a href="#" type="button">ADD TO CARD</a>
              </div>
              <div class="product-desc">
                <p>Proin sed nulla mi</p>
                <div class="rate mt-1">
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star"></i></span>
                </div>
                <div class="d-flex mt-1">
                  <p class="new-price">$84.00</p>
                </div>
              </div>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
                <div class="product-top">
                  <img src="/images/productions/01_homepage_7.jpg">
                  <a href="#" type="button">ADD TO CARD</a>
                </div>
                <div class="product-desc">
                  <p>Aenean placerat</p>
                  <div class="rate mt-1">
                    <span><i class="far fa-star star-rated"></i></span>
                    <span><i class="far fa-star star-rated"></i></span>
                    <span><i class="far fa-star star-rated"></i></span>
                    <span><i class="far fa-star star-rated"></i></span>
                    <span><i class="far fa-star star-rated"></i></span>
                  </div>
                  <div class="d-flex mt-1">
                    <p class="old-price">$99.00</p>
                    <p class="new-price">$84.00</p>
                  </div>
                </div>
              </div>
        </div>

      <div class="row mt-5">
        <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
          <div class="product-top">
            <img src="/images/productions/01_homepage_8.jpg">
            <a href="#" type="button">ADD TO CARD</a>
          </div>
          <div class="product-desc">
            <p>Suspendisse id volutpat</p>
            <div class="rate mt-1">
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star star-rated"></i></span>
              <span><i class="far fa-star"></i></span>
            </div>
            <div class="d-flex mt-1">
              <p class="old-price">$99.00</p>
              <p class="new-price">$84.00</p>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
            <div class="product-top">
              <img src="/images/productions/01_homepage_9.jpg">
              <a href="#" type="button">ADD TO CARD</a>
            </div>
            <div class="product-desc">
              <p>Lorem ipsum dolor</p>
              <div class="rate mt-1">
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star"></i></span>
              </div>
              <div class="d-flex mt-1">
                <p class="old-price">$99.00</p>
                <p class="new-price">$84.00</p>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
            <div class="product-top">
              <img src="/images/productions/01_homepage_10.jpg">
              <a href="#" type="button">ADD TO CARD</a>
            </div>
            <div class="product-desc">
              <p>Proin sed nulla mi</p>
              <div class="rate mt-1">
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star star-rated"></i></span>
                <span><i class="far fa-star"></i></span>
              </div>
              <div class="d-flex mt-1">
                <p class="new-price">$84.00</p>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-4 col-sm-6 col-sx-12">
              <div class="product-top">
                <img src="/images/productions/01_homepage_11.jpg">
                <a href="#" type="button">ADD TO CARD</a>
              </div>
              <div class="product-desc">
                <p>Aenean placerat</p>
                <div class="rate mt-1">
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star star-rated"></i></span>
                  <span><i class="far fa-star star-rated"></i></span>
                </div>
                <div class="d-flex mt-1">
                  <p class="old-price">$99.00</p>
                  <p class="new-price">$84.00</p>
                </div>
              </div>
          </div>
        </div>
    </div>
  </div>

</div>
</div>
<!-- BLOGS -->
<div class="blog mt-5">
  <div class="col-md-8 main-content">
    <div class="blog-title">
      <p class="text-logo">L A T E S T</p>
      <p class="title-p">NEWS & EVENTS</p>
      <div class="border-blog-title"></div>
    </div>

    <div class="container mt-5">
        <div id="carousel-blog" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-blog" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-blog" data-slide-to="1"></li>
                <li data-target="#carousel-blog" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active" data-interval="10000">
                <div class="row">
                <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                  <img src="/images/blog/01_homepage_13.jpg" class="d-block w-100" alt="first image">
                  <div class="blog-label">
                    <div class="border-label">
                      <p class="mt-1">Jan </p>
                      <p>23 </p>
                    </div>
                  </div>
                  <div class="blog-info">
                    <a href="#">Incommodo dolor vitea</a>
                    <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                    <div class="border-blog"></div>
                    <div class="blog-icon">
                      <span><i class="far fa-comment">12</i></span>
                      <span class="ml-4"><i class="far fa-heart">6</i></span>
                    </div>
                  </div>
                </div>
                <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                    <img src="/images/blog/01_homepage_14.jpg" class="d-block w-100" alt="first image">
                    <div class="blog-label">
                      <div class="border-label">
                        <p class="mt-1">Jan </p>
                        <p>23 </p>
                      </div></div>
                    <div class="blog-info">
                      <a href="#">Vivamus non dignissim elit</a>
                      <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                      <div class="border-blog"></div>
                      <div class="blog-icon">
                        <span><i class="far fa-comment">12</i></span>
                        <span class="ml-4"><i class="far fa-heart">6</i></span>
                      </div>
                    </div>
                </div>
                <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                    <img src="/images/blog/01_homepage_15.jpg" class="d-block w-100" alt="first image">
                    <div class="blog-label">
                      <div class="border-label">
                        <p class="mt-1">Jan </p>
                        <p>23 </p>
                      </div></div>
                    <div class="blog-info">
                      <a href="#">Ut lacinia erat ut diam volutpat</a>
                      <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                      <div class="border-blog"></div>
                      <div class="blog-icon">
                        <span><i class="far fa-comment">12</i></span>
                        <span class="ml-4"><i class="far fa-heart">6</i></span>
                      </div>
                    </div>
                </div>
              </div>
              </div>
              <div class="carousel-item" data-interval="2000">
                <div class="row">
                    <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                      <img src="/images/blog/01_homepage_14.jpg" class="d-block w-100" alt="first image">
                      <div class="blog-label">
                        <div class="border-label">
                          <p class="mt-1">Jan</p>
                          <p>23</p>
                        </div></div>
                      <div class="blog-info">
                        <a href="#">Incommodo dolor vitea</a>
                        <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                        <div class="border-blog"></div>
                        <div class="blog-icon">
                          <span><i class="far fa-comment">12</i></span>
                          <span class="ml-4"><i class="far fa-heart">6</i></span>
                        </div>
                      </div>
                    </div>
                    <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                      <img src="/images/blog/01_homepage_15.jpg" class="d-block w-100" alt="first image">
                      <div class="blog-label">
                        <div class="border-label">
                          <p class="mt-1">Jan </p>
                          <p>23 </p>
                        </div>  
                      </div>
                      <div class="blog-info">
                        <a href="#">Vivamus non dignissim elit</a>
                        <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                        <div class="border-blog"></div>
                        <div class="blog-icon">
                          <span><i class="far fa-comment">12</i></span>
                          <span class="ml-4"><i class="far fa-heart">6</i></span>
                        </div>
                      </div>
                    </div>
                    <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                      <img src="/images/blog/01_homepage_13.jpg" class="d-block w-100" alt="first image">
                      <div class="blog-label">
                        <div class="border-label">
                          <p class="mt-1">Jan </p>
                          <p>23 </p>
                        </div>
                      </div>
                      <div class="blog-info">
                        <a href="#">Ut lacinia erat ut diam volutpat</a>
                        <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                        <div class="border-blog"></div>
                        <div class="blog-icon">
                          <span><i class="far fa-comment">12</i></span>
                          <span class="ml-4"><i class="far fa-heart">6</i></span>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="carousel-item">
                <div class="row">
                  <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                    <img src="/images/blog/01_homepage_15.jpg" class="d-block w-100" alt="first image">
                    <div class="blog-label">
                      <div class="border-label">
                        <p class="mt-1">Jan </p>
                        <p>23 </p>
                      </div></div>
                    <div class="blog-info">
                      <a href="#">Incommodo dolor vitea</a>
                      <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                      <div class="border-blog"></div>
                      <div class="blog-icon">
                        <span><i class="far fa-comment">12</i></span>
                        <span class="ml-4"><i class="far fa-heart">6</i></span>
                      </div>
                    </div>
                  </div>
                  <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                      <img src="/images/blog/01_homepage_13.jpg" class="d-block w-100" alt="first image">
                      <div class="blog-label"> 
                        <div class="border-label">
                          <p class="mt-1">Jan </p>
                          <p>23 </p>
                        </div></div>
                      <div class="blog-info">
                        <a href="#">Vivamus non dignissim elit</a>
                        <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                        <div class="border-blog"></div>
                        <div class="blog-icon">
                          <span><i class="far fa-comment">12</i></span>
                          <span class="ml-4"><i class="far fa-heart">6</i></span>
                        </div>
                      </div>
                    </div>
                    <div class="positive-img col-md-4 col-sm-6 col-sm-12">
                      <img src="/images/blog/01_homepage_14.jpg" class="d-block w-100" alt="first image">
                      <div class="blog-label"> 
                        <div class="border-label">
                          <p class="mt-1">Jan </p>
                          <p>23 </p>
                        </div>
                      </div>
                      <div class="blog-info">
                        <a href="#">Ut lacinia erat ut diam volutpat</a>
                        <p>Aliquam tempor sagittis neque, vel qliquam risus consectetur vel, Aenean hendrerit, elit a lacinia suscipit, orrci mauris.</p>
                        <div class="border-blog"></div>
                        <div class="blog-icon">
                          <span><i class="far fa-comment">12</i></span>
                          <span class="ml-4"><i class="far fa-heart">6</i></span>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</div>
