<div class="container">
	<form method='POST' action="/magento2/blog/index/save">
	    <div class="form-group">
	        <label for="name">Name</label>
	        <input type="text" class="form-control" id="name" placeholder="Enter a name" name="name">
	    </div>

	    <div class="form-group">
	        <label for="url_key">Url Key</label>
	        <input type="text" class="form-control" id="url_key" placeholder="Enter a url key" name="url_key">
	    </div>
		<div class="form-group">
	        <label for="image">Image</label>
	        <input type="text" class="form-control" id="image" placeholder="Enter a image" name="image">
	    </div>
	    <div class="form-group">
	        <label for="organization">Content</label>
	        <input type="text" class="form-control" id="content" placeholder="Enter a organization" name="content">
	    </div>
	    <div class="form-group">
	        <label for="number">Status</label>
	        <input type="number" class="form-control" id="status" placeholder="Enter a number" name="status">
	    </div>
	    <button type="submit" class="btn btn-primary" name="createbtn">Submit</button>
	</form>
</div>